# Generated by Django 3.0.2 on 2020-01-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salt',
            name='profile_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
