# Generated by Django 3.0.2 on 2020-01-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_salt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salt',
        ),
    ]
