# Generated by Django 3.0.2 on 2020-01-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_remove_myuser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('value', models.CharField(max_length=32)),
            ],
        ),
    ]
