# Generated by Django 3.0.2 on 2020-01-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_auto_20200130_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_joined',
        ),
    ]
