# Generated by Django 3.0.2 on 2020-01-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0005_remove_myuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('0', '일반 유저'), ('5', '세탁소 사장'), ('10', '관리자')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
