# Generated by Django 3.0.2 on 2020-01-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0006_myuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
    ]
